### ISSUE TITLE
Implement IANA model and BibXML

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iana#1]
Data source is available here:

https://github.com/ietf-ribose/iana-registries

e.g.
https://raw.githubusercontent.com/ietf-ribose/iana-registries/main/service-names-port-numbers/service-names-port-numbers.xml

Output in a manner like https://xml2rfc.tools.ietf.org/public/rfc/bibxml-iana/reference.IANA.service-names-port-numbers.xml

```xml
<reference anchor="SERVICE-NAMES-PORT-NUMBERS" target="http://www.iana.org/assignments/service-names-port-numbers">
<front>
<title>
Service Name and Transport Protocol Port Number Registry
</title>
<author>
<organization>IANA</organization>
</author>
<date/>
</front>
</reference>
```

**Comment by andrew2net** [comment]
@ronaldtse should we use the  https://xml2rfc.tools.ietf.org/public/rfc/bibxml-iana/ as a data source?

**Comment by ronaldtse** [comment]
@andrew2net No... See this: https://github.com/ietf-ribose/bibxml-data-iana/issues/2
