### ISSUE TITLE
(URGENT) Failure in relaton-data-iana fetching

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iana#12]
https://github.com/ietf-tools/relaton-data-iana/actions/runs/2645097830

Since the ietf-ribose/iana-registries repo was moved to ietf-tools/iana-registries , the ietf-tools/relaton-data-iana tools GHA workflows have been failing.

We have to fix it ASAP.

**Comment by andrew2net** [comment]
fixed in v 1.12.3 but I don't have permission to run GHA on ietf-tools/relaton-data-iana repo manually.

**Comment by ronaldtse** [comment]
Confirm fixed. <img width="1276" alt="Screenshot 2022-07-12 at 7 42 03 PM" src="https://user-images.githubusercontent.com/11865/178472452-15114509-ba8f-410b-9ee2-df6e07220cc5.png">
