### ISSUE TITLE
(URGENT) Structural discrepancies in Relaton-IANA data files

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iana#15]
From https://github.com/relaton/relaton/issues/108

There are structural discrepancies reported by @strogonoff.

> * [IANA](https://raw.githubusercontent.com/ietf-tools/relaton-data-iana/main/data/bgp-extended-communities_arp-nd-extended-community-flags.yaml):
> 
> ```
> contributor -> 0 -> organization -> abbreviation
>   str type expected (type=type_error.str)
> ```

**Comment by andrew2net** [comment]
@ronaldtse since we dropped simplifying the YAML output, the abbreviation is rendered as an object.
As @strogonoff said the bixml-service is adopted to consume objects.
