### ISSUE TITLE
(URGENT) ietf-tools/relaton-data-iana hitting rate limit on GitHub

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iana#16]
https://github.com/ietf-tools/relaton-data-iana/actions/runs/3621439925/jobs/6104878051

**Comment by andrew2net** [comment]
@ronaldtse it's [a secondary rate limit](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#secondary-rate-limits). It happens from time to time. I didn't find any recommendation how to avoid it. Will try to increase pauses between API requests.

**Comment by ronaldtse** [comment]
Thank you @andrew2net , closing.
