### ISSUE TITLE
Individual registries should be citable

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iana#2]
We need to distinguish between:
* named registry collection
* registry

In the current implementation at bibxml8, an IANA table is represented like this:
https://xml2rfc.tools.ietf.org/public/rfc/bibxml8/reference.IANA.rpki.xml

This file represents an "IANA table” (in BibXML speak according to xml2rfc.tools.ietf.org). It actually represents an IANA page that provides a set of individual registries that belong to the same protocol.

For example, https://www.iana.org/assignments/rpki/rpki.xhtml is the "Resource Public Key Infrastructure (RPKI)” registry collection, it contains 7 individual registries:
“
Registries included below
	• RPKI Signed Objects
	• RPKI Repository Name Schemes
	• rpki-rtr-pdu
	• rpki-rtr-error
	• BGPsec Capability
	• BGPsec_Path Flags
	• BGPsec Algorithm Suites
“

Technically, a registry can be mandated by a different RFC.

We should make both types citable:
* named registry collection: e.g. "Resource Public Key Infrastructure (RPKI) registry collection"
* registry: e.g. "RPKI Signed Objects"

We need to update the Relaton IANA model and also the relaton-iana implementation.

**Comment by andrew2net** [comment]
@ronaldtse should we use for included registries collection's link and publish date?

**Comment by ronaldtse** [comment]
Yes for both. For each registry it also has a fragment anchor link, so let's use that one.

**Comment by andrew2net** [comment]
@ronaldtse some collections have included registries with id which conflicts with other registry. For example a collection [ppspp](https://github.com/ietf-ribose/iana-registries/blob/main/ppspp/ppspp.xml) has included registry with id `message-types` which conflicts with same named registry in a collection [manet-parameters](https://github.com/ietf-ribose/iana-registries/blob/main/manet-parameters/manet-parameters.xml).
Shouldn't we compose a cllection's id with included registry's id? For example `papp-message-types` and `manet-parameters-message-types`.

**Comment by ronaldtse** [comment]
Yes we should. But maybe not a `-` as the separator?

How about:

* `manet-parameters/message-types` or
* `manet-parameters#message-types`
?

**Comment by ronaldtse** [comment]
I think a `/` makes more sense here.

**Comment by andrew2net** [comment]
@ronaldtse there are three collections that have registries without titles:
- https://raw.githubusercontent.com/ietf-ribose/iana-registries/main/ipv6-address-space/ipv6-address-space.xml
- https://raw.githubusercontent.com/ietf-ribose/iana-registries/main/ip-xns-mapping/ip-xns-mapping.xml
- https://raw.githubusercontent.com/ietf-ribose/iana-registries/main/pidf-lo-civic-address-consideration-registry/pidf-lo-civic-address-consideration-registry.xml

Shouldn't we skip these registries?

These two files are redirections to specific version:
- https://raw.githubusercontent.com/ietf-ribose/iana-registries/main/precis-tables/precis-tables.xml
- https://raw.githubusercontent.com/ietf-ribose/iana-registries/main/idna-tables/idna-tables.xml

What should we do with them?

**Comment by ronaldtse** [comment]
> @ronaldtse there are three collections that have registries without titles:

Let's use the `id=` to be their title for now.

> These two files are redirections to specific version:

We should ignore them.
