### ISSUE TITLE
Use https scheme for links to IANA registries

### ISSUE THREAD

**Issue by jumpifnotzero** [relaton/relaton-iana#22]
Hi,

I've been chasing down a question from the IETF as to why the links to IANA registries don't use the https scheme. I believe this project is the source of that data. See https://bib.ietf.org/get-one/by-docid/?doctype=IANA&docid=IANA%20core-parameters%2Frd-parameters. 

I am not familiar with Ruby, however it appears the links are constructed by joining the XML namespace with the value of the @id attribute, see below. Can you please replace the scheme with https?

https://github.com/relaton/relaton-iana/blob/b4b0f3dd6a5b3f865b02bc99d56eb9440c196e22/lib/relaton_iana/parser.rb#L61-L67

**Comment by andrew2net** [comment]
Hi @jumpifnotzero,

Thank you for pointing this out.
Of course, we can replace http with https, but the schema comes from IANA [dataset](https://github.com/ietf-tools/iana-registries/blob/ab21acaad25a91fe5a4db4ef995b77be20628ceb/core-parameters/core-parameters.xml#L4). I'm not sure if the replacement will be correct for all the links. @ronaldtse what do you think?

**Comment by jumpifnotzero** [comment]
I suggest that you simply join the literal URL "https://www.iana.org/assignments" with the identifier. IANA will ensure those links remain stable as they are cited in immutable documents such as RFCs.

The reason for this suggestion is that the XML namespace is just that, an XML namespace. It happens to be the base path to the resource using http, however the XML namespace will not be updated to reflect a canonical or preferred URL for that resource.

It does seem the dataset is missing a self link relation.

**Comment by opoudjis** [comment]
> It does seem the dataset is missing a self link relation.

@andrew2net We can just make that `/uri[@type = 'self']`, no need to create a more generic type name that IETF would be unfamiliar with.

**Comment by andrew2net** [comment]
@jumpifnotzero I checked the IANA links. You are right, they all are URL "https://www.iana.org/assignments" with the identifier. Will update them shortly.

**Comment by andrew2net** [comment]
Done https://github.com/relaton/relaton-data-iana/blob/ca693f32481b9f24cb6fb9b89981b6297cca29e1/data/_6lowpan-parameters.yaml#L8

**Comment by ronaldtse** [comment]
Thank you @jumpifnotzero for reporting! Thanks @andrew2net and @opoudjis for resolving this!
