### ISSUE TITLE
Provide IANA `type=IETF scope=anchor` value to uppercase of "ID"

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-iana#5]
As per official IETF from https://github.com/ietf-ribose/bibxml-service/issues/151#issuecomment-1066424025 , IANA bibliographic references must have an anchor that is the uppercased version of the ID.

> * bibxml8/IANA. https://xml2rfc.tools.ietf.org/public/rfc/bibxml8/reference.IANA.dns-parameters.xml => anchor of "DNS-PARAMETERS" (upper case of filename)

**Comment by andrew2net** [comment]
@ronaldtse should the anchor be `DNS-PARAMETERS` or `IANA.DNS-PARAMETERS`?

**Comment by ronaldtse** [comment]
@andrew2net just "DNS-PARAMETERS" as per the file. Thanks!

**Comment by ronaldtse** [comment]
Thanks @andrew2net !

**Comment by ronaldtse** [comment]
@andrew2net will this change be reflected in relaton-data-iana shortly? Thanks!

**Comment by andrew2net** [comment]
@ronaldtse this change impacts only BibXML. It's reflected in bibxml-data-iana.

**Comment by ronaldtse** [comment]
@andrew2net we have to place it in the Relaton format, i.e. relaton-data-iana. The BibXML service no longer uses bibxml-data-iana.

**Comment by ronaldtse** [comment]
i.e. please put an extra identifier here for IETF with `scope` anchor:
https://github.com/ietf-ribose/relaton-data-iana/blob/246634b4712575cd997dc128c03711df232765df/data/_6lowpan-parameters.yaml#L10-L13

**Comment by andrew2net** [comment]
done

**Comment by ronaldtse** [comment]
Can see it now, thanks!

https://github.com/ietf-ribose/relaton-data-iana/blob/3b2cda1a0d184c19b74c8f296d74ee2a46ef85cb/data/_6lowpan-parameters.yaml#L14-L16

**Comment by ronaldtse** [comment]
However, I'm not sure about these:
https://github.com/ietf-ribose/relaton-data-iana/blob/3b2cda1a0d184c19b74c8f296d74ee2a46ef85cb/data/ace_ace-profiles.yaml#L14-L16

https://github.com/ietf-ribose/relaton-data-iana/blob/3b2cda1a0d184c19b74c8f296d74ee2a46ef85cb/data/dns-parameters_zonemd-schemes.yaml#L14-L16

I don't think the anchor can contain `/`. Maybe we change them to `.`?
